[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
ffi = false
via_ir = true
remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "short"
quote_style = "double"
